[build]
  publish = "dist"
  command = "yarn generate"


 
        [[redirects]]
          from = "/blog"
          to = "https://nuxttest.superblog.cloud/"
          status = 200
          force = true

        [[redirects]]
          from = "/blog/*"
          to = "https://nuxttest.superblog.cloud/:splat"
          status = 200
          force = true

        [[redirects]]
          from = "/_elderjs/*"
          to = "https://nuxttest.superblog.cloud/_elderjs/:splat"
          status = 200 
          force = true

